### ISSUE TITLE
Model selection.

### ISSUE THREAD

**Issue by jdamboeck** [alisson-anjos/ComfyUI-Ollama-Describer#5]
Is there a reason for pre-selecting possible models instead of just give a selection of installed models?

**Comment by alisson-anjos** [comment]
> Is there a reason for pre-selecting possible models instead of just give a selection of installed models?

Hello, so the idea was to make some models available as soon as the person installs the custom node, because otherwise the list will appear blank, now with the custom_model it would be possible to do the installation by putting a value in that field and then in the model field list the models that are already installed, other than that there is the issue of classifying which models are vision models and which ones do not have this feature, there is no way for me to know other than leaving this information previously set in the code.

**Comment by jdamboeck** [comment]
Maybe some kind of override would be good? Or a second node? I would really like to use your node but with the models i have installed.

**Comment by jdamboeck** [comment]
I see you already did it :)
Awesome thank you!

**Comment by alisson-anjos** [comment]
> I see you already did it :) Awesome thank you!

So, I added the possibility of selecting a custom_model, but it is still something that you need to type the name of the model, but with that you can already use your models, you just need to pay attention to the issue that for Ollama Image Describer you need to use a model that is multimodal (with vision), I will see a way to extract the information directly from ollama to find out if a model supports vision and list the ones installed on the machine.

**Comment by jdamboeck** [comment]
Yeah i was just about to write as i saw the update. Nice. Everything there i need. But sure. For some it may be better to know which models they can use.
